-- Historial mínimo para cruces de asistencia, ausentismo y descanso efectivo.
create table if not exists public.attendance_snapshots (
  id bigint generated by default as identity primary key,
  operational_date date not null,
  contractor text not null,
  file_name text not null default '',
  rows jsonb not null default '[]'::jsonb,
  uploaded_by uuid not null default auth.uid(),
  uploaded_at timestamptz not null default now(),
  closed_at timestamptz,
  unique (operational_date, contractor)
);

alter table public.attendance_snapshots enable row level security;
grant select, insert, update on table public.attendance_snapshots to authenticated;
grant usage, select on sequence public.attendance_snapshots_id_seq to authenticated;

create or replace function public.can_access_attendance_contractor(value text)
returns boolean
language sql
stable
as $$
  select
    lower(coalesce(auth.jwt() ->> 'email', '')) in ('admin@bavaria-seguimiento.com', 'people@transporte.com')
    or lower(value) = case lower(coalesce(auth.jwt() ->> 'email', ''))
      when 'logisticos@bavaria-seguimiento.com' then 'logisticos'
      when 'puntocorona@bavaria-seguimiento.com' then 'punto corona'
      when 'surticervezas@bavaria-seguimiento.com' then 'surti cervezas'
      when 'logisticos@transporte.com' then 'logisticos arenosa'
      when 'corona@transporte.com' then 'punto corona arenosa'
      else ''
    end;
$$;

drop policy if exists "attendance lectura por contratista" on public.attendance_snapshots;
create policy "attendance lectura por contratista" on public.attendance_snapshots
for select to authenticated using (public.can_access_attendance_contractor(contractor));

drop policy if exists "attendance insercion por contratista" on public.attendance_snapshots;
create policy "attendance insercion por contratista" on public.attendance_snapshots
for insert to authenticated with check (
  uploaded_by = auth.uid() and public.can_access_attendance_contractor(contractor)
);

drop policy if exists "attendance actualizacion por contratista" on public.attendance_snapshots;
create policy "attendance actualizacion por contratista" on public.attendance_snapshots
for update to authenticated
using (public.can_access_attendance_contractor(contractor))
with check (public.can_access_attendance_contractor(contractor));
