create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  contractor text not null,
  is_admin boolean not null default false,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "users manage own push subscription" on public.push_subscriptions;
create policy "users manage own push subscription"
on public.push_subscriptions
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on table public.push_subscriptions from anon;
grant select, insert, update, delete on table public.push_subscriptions to authenticated;

comment on table public.push_subscriptions is 'Suscripciones Web Push; el backend solo envía alertas operativas al administrador.';

create table if not exists public.push_notification_state (
  notification_key text primary key,
  fingerprint text not null,
  sent_at timestamptz not null default now()
);

alter table public.push_notification_state enable row level security;
revoke all on table public.push_notification_state from anon, authenticated;
