-- Agrega advertencias operativas por barrio/ruta.
-- Separe varias advertencias con punto y coma o saltos de linea.
alter table public.ruta_criticas
add column if not exists "ADVERTENCIAS" text not null default '';

comment on column public.ruta_criticas."ADVERTENCIAS" is
'Riesgos conocidos: cables bajos, huecos, inundacion, cierre vial u otros.';

-- Ejemplo:
-- update public.ruta_criticas
-- set "ADVERTENCIAS" = 'Cables bajos en la entrada; Vía con huecos después del puente'
-- where "RUTA" ilike 'LAS MALVINAS%';

-- Señales que aparecerán en puntos exactos del mapa.
create table if not exists public.ruta_criticas_riesgos (
  id bigint generated by default as identity primary key,
  ruta text not null,
  tipo text not null default 'peligro'
    check (tipo in ('cables_bajos', 'via_danada', 'inundacion', 'cierre', 'peligro')),
  descripcion text not null,
  latitud double precision not null check (latitud between -90 and 90),
  longitud double precision not null check (longitud between -180 and 180),
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

alter table public.ruta_criticas_riesgos enable row level security;
grant select, insert, delete on table public.ruta_criticas_riesgos to authenticated;
grant usage, select on sequence public.ruta_criticas_riesgos_id_seq to authenticated;
grant select, insert on table public.ruta_criticas_riesgos to anon;
grant usage, select on sequence public.ruta_criticas_riesgos_id_seq to anon;

drop policy if exists "Riesgos de rutas lectura autenticada" on public.ruta_criticas_riesgos;
create policy "Riesgos de rutas lectura autenticada"
on public.ruta_criticas_riesgos for select to authenticated using (true);

drop policy if exists "Riesgos de rutas escritura autenticada" on public.ruta_criticas_riesgos;
create policy "Riesgos de rutas escritura autenticada"
on public.ruta_criticas_riesgos for insert to authenticated with check (true);

drop policy if exists "Riesgos de rutas eliminacion autenticada" on public.ruta_criticas_riesgos;
create policy "Riesgos de rutas eliminacion autenticada"
on public.ruta_criticas_riesgos for delete to authenticated using (true);

drop policy if exists "Riesgos de rutas lectura publica" on public.ruta_criticas_riesgos;
create policy "Riesgos de rutas lectura publica"
on public.ruta_criticas_riesgos for select to anon using (activo = true);

drop policy if exists "Riesgos de rutas reporte publico" on public.ruta_criticas_riesgos;
create policy "Riesgos de rutas reporte publico"
on public.ruta_criticas_riesgos for insert to anon
with check (activo = true and char_length(descripcion) between 3 and 240);

-- Ejemplo de una señal (reemplace las coordenadas por el punto real):
-- insert into public.ruta_criticas_riesgos
--   (ruta, tipo, descripcion, latitud, longitud)
-- values
--   ('LAS MALVINAS', 'cables_bajos', 'Cables bajos: altura máxima 3,5 m', 10.9300, -74.8500);
