-- Ejecutar completo en el SQL Editor de Supabase.
-- Conserva las rutas existentes y sus advertencias; no modifica permisos.
-- Requiere public.ruta_criticas con "#" num?rico, "RUTA" y "CD".
-- Fuente: 280 filas, 269 pares RUTA/CD distintos.
-- Se omiten repetidos exactos; los nombres se conservan como se suministraron.
-- ATENCI?N: las API p?blica y People del cat?logo tienen limit: "200".
-- Es necesario paginar esas consultas para mostrar todo el cat?logo.

begin;

-- Evita asignar n?meros repetidos si hay otra carga simult?nea.
lock table public.ruta_criticas in share row exclusive mode;

with nuevas (orden, ruta, cd) as (
  values
  (1, 'Altos de Jesús', 'GALAPA'),
  (2, 'Altos de la Metropolitana', 'GALAPA'),
  (3, 'Altos de la Villa', 'GALAPA'),
  (4, 'Altos de los Almendros', 'GALAPA'),
  (5, 'Altos de los Robles', 'GALAPA'),
  (6, 'Antonio Nariño', 'GALAPA'),
  (7, 'Barrio Centro', 'GALAPA'),
  (8, 'Bella Jerusalén', 'GALAPA'),
  (9, 'Bella Murillo', 'GALAPA'),
  (10, 'Ciudad Bolívar', 'GALAPA'),
  (11, 'Ciudad Bonita', 'GALAPA'),
  (12, 'Ciudad Camelot', 'GALAPA'),
  (13, 'Ciudad Caribe', 'GALAPA'),
  (14, 'Ciudad Caribe IV', 'GALAPA'),
  (15, 'Ciudad Paraíso', 'GALAPA'),
  (16, 'Ciudad Salitre', 'GALAPA'),
  (17, 'Ciudad Transmetro', 'GALAPA'),
  (18, 'Ciudadela Metropolitana', 'GALAPA'),
  (19, 'Cruz de Mayo', 'GALAPA'),
  (20, 'Doce de Octubre', 'GALAPA'),
  (21, 'Don Bosco', 'GALAPA'),
  (22, 'El Carnero', 'GALAPA'),
  (23, 'El Cortijo', 'GALAPA'),
  (24, 'El Esfuerzo', 'GALAPA'),
  (25, 'El Ferrocarril', 'GALAPA'),
  (26, 'El Hipódromo', 'GALAPA'),
  (27, 'El Oasis', 'GALAPA'),
  (28, 'El Porvenir', 'GALAPA'),
  (29, 'El Triunfo', 'GALAPA'),
  (30, 'Juan Domínguez Romero', 'GALAPA'),
  (31, 'La Arboleda', 'GALAPA'),
  (32, 'La Bonanza', 'GALAPA'),
  (33, 'La Candelaria', 'GALAPA'),
  (34, 'La Candelaria I', 'GALAPA'),
  (35, 'La Candelaria II', 'GALAPA'),
  (36, 'La Central', 'GALAPA'),
  (37, 'La Esperanza', 'GALAPA'),
  (38, 'La Farruca', 'GALAPA'),
  (39, 'La Fe', 'GALAPA'),
  (40, 'La Ilusión', 'GALAPA'),
  (41, 'La Inmaculada', 'GALAPA'),
  (42, 'La Loma', 'GALAPA'),
  (43, 'La María', 'GALAPA'),
  (44, 'La Rivera', 'GALAPA'),
  (45, 'La Victoria', 'GALAPA'),
  (46, 'Las Moras IV', 'GALAPA'),
  (47, 'Las Moras Norte', 'GALAPA'),
  (48, 'Las Nubes', 'GALAPA'),
  (49, 'Las Trinitarias', 'GALAPA'),
  (50, 'Linda María', 'GALAPA'),
  (51, 'Los Almendros', 'GALAPA'),
  (52, 'Los Almendros II', 'GALAPA'),
  (53, 'Los Almendros III', 'GALAPA'),
  (54, 'Los Cedros', 'GALAPA'),
  (55, 'Los Cusules', 'GALAPA'),
  (56, 'Los Fundadores', 'GALAPA'),
  (57, 'Los Loteros', 'GALAPA'),
  (58, 'Los Robles', 'GALAPA'),
  (59, 'Los Rosales', 'GALAPA'),
  (60, 'Manuela Beltrán', 'GALAPA'),
  (61, 'Montecarmelo', 'GALAPA'),
  (62, 'Nuevo Éxito', 'GALAPA'),
  (63, 'Nuevo Horizonte', 'GALAPA'),
  (64, 'Nuevo Milenio', 'GALAPA'),
  (65, 'Nuevo Triunfo', 'GALAPA'),
  (66, 'Portal de los Nogales', 'GALAPA'),
  (67, 'Prado de Soledad', 'GALAPA'),
  (68, 'Primero de Mayo', 'GALAPA'),
  (69, 'Pumarejo', 'GALAPA'),
  (70, 'Reserva de los Almendros', 'GALAPA'),
  (71, 'Salamanca', 'GALAPA'),
  (72, 'Salcedo', 'GALAPA'),
  (73, 'San Antonio', 'GALAPA'),
  (74, 'Si Nos Dejan', 'GALAPA'),
  (75, 'Siete de Agosto', 'GALAPA'),
  (76, 'Soledad 2000', 'GALAPA'),
  (77, 'Tajamar', 'GALAPA'),
  (78, 'Urbanización Las Moras', 'GALAPA'),
  (79, 'Urbanización María de los Ángeles', 'GALAPA'),
  (80, 'Urbanización Villa Soledad', 'GALAPA'),
  (81, 'Veinte de Julio', 'GALAPA'),
  (82, 'Villa Adela I', 'GALAPA'),
  (83, 'Villa Adela II', 'GALAPA'),
  (84, 'Villa Angelita', 'GALAPA'),
  (85, 'Villa Anita', 'GALAPA'),
  (86, 'Villa Carmen I', 'GALAPA'),
  (87, 'Villa Carmen II', 'GALAPA'),
  (88, 'Villa Cecilia', 'GALAPA'),
  (89, 'Villa de Aragón', 'GALAPA'),
  (90, 'Villa del Carmen', 'GALAPA'),
  (91, 'Villa del Rey', 'GALAPA'),
  (92, 'Villa Estadio', 'GALAPA'),
  (93, 'Villa Estefany', 'GALAPA'),
  (94, 'Villa Esther', 'GALAPA'),
  (95, 'Villa Katanga', 'GALAPA'),
  (96, 'Villa Katanga II', 'GALAPA'),
  (97, 'Villa Las Moras I', 'GALAPA'),
  (98, 'Villa Lozano', 'GALAPA'),
  (99, 'Villa Rosa', 'GALAPA'),
  (100, 'Villa Santa', 'GALAPA'),
  (101, 'Villa Severa', 'GALAPA'),
  (102, 'Villa Sevilla', 'GALAPA'),
  (103, 'Villa Soledad', 'GALAPA'),
  (104, 'Villa Valentina', 'GALAPA'),
  (105, 'Villa Zambrano', 'GALAPA'),
  (106, 'Viñas del Rey', 'GALAPA'),
  (107, 'Vista Hermosa', 'GALAPA'),
  (108, 'Zarabanda', 'GALAPA'),
  (109, 'Abajo', 'GALAPA'),
  (110, 'Alfonso López', 'GALAPA'),
  (111, 'Altamira', 'GALAPA'),
  (112, 'Altos de Riomar', 'GALAPA'),
  (113, 'Buenos Aires', 'GALAPA'),
  (114, 'Carrizal', 'GALAPA'),
  (115, 'Chiquinquirá', 'GALAPA'),
  (116, 'El Campito', 'GALAPA'),
  (117, 'El Limón', 'GALAPA'),
  (118, 'El Milagro', 'GALAPA'),
  (119, 'El Parque Sector Barranquilla', 'GALAPA'),
  (120, 'El Poblado', 'GALAPA'),
  (121, 'José Antonio Galán', 'GALAPA'),
  (122, 'La Arboraya', 'GALAPA'),
  (123, 'La Chinita', 'GALAPA'),
  (124, 'La Luz', 'GALAPA'),
  (125, 'La Unión', 'GALAPA'),
  (126, 'Las Dunas', 'GALAPA'),
  (127, 'Las Nieves', 'GALAPA'),
  (128, 'La Floresta', 'GALAPA'),
  (129, 'Rebolo', 'GALAPA'),
  (130, 'Riomar', 'GALAPA'),
  (131, 'San Salvador', 'GALAPA'),
  (132, 'Villa Carolina', 'GALAPA'),
  (133, 'Villa Country', 'GALAPA'),
  (134, '20 de Julio', 'GALAPA'),
  (135, 'Caldas', 'GALAPA'),
  (136, 'Chambacú', 'GALAPA'),
  (137, 'El Muelle', 'GALAPA'),
  (138, 'El Pradito', 'GALAPA'),
  (139, 'España Norte', 'GALAPA'),
  (140, 'España Sur', 'GALAPA'),
  (141, 'Góngora', 'GALAPA'),
  (142, 'Guayabal', 'GALAPA'),
  (143, 'La Ceiba', 'GALAPA'),
  (144, 'Las Américas', 'GALAPA'),
  (145, 'Las Margaritas', 'GALAPA'),
  (146, 'Loma Fresca Norte', 'GALAPA'),
  (147, 'Loma Fresca Sur', 'GALAPA'),
  (148, 'Manzanares', 'GALAPA'),
  (149, 'Once de Noviembre', 'GALAPA'),
  (150, 'Paraíso', 'GALAPA'),
  (151, 'Piñique', 'GALAPA'),
  (152, 'Porvenir', 'GALAPA'),
  (153, 'Primavera', 'GALAPA'),
  (154, 'Primero de Enero', 'GALAPA'),
  (155, 'San Cayetano', 'GALAPA'),
  (156, 'San José', 'GALAPA'),
  (157, 'San Martín', 'GALAPA'),
  (158, 'Santa Ana', 'GALAPA'),
  (159, 'Santa Elena', 'GALAPA'),
  (160, 'Siete de Octubre', 'GALAPA'),
  (161, 'Topacio', 'GALAPA'),
  (162, 'Urbanización Barahona', 'GALAPA'),
  (163, 'Urbanización Ciudadela La Paz', 'GALAPA'),
  (164, 'Urbanización El Carmen', 'GALAPA'),
  (165, 'Urbanización El Encanto', 'GALAPA'),
  (166, 'Urbanización Los Robles', 'GALAPA'),
  (167, 'Urbanización San José', 'GALAPA'),
  (168, 'Urbanización Torcoroma', 'GALAPA'),
  (169, 'Urbanización Villa Eleyta', 'GALAPA'),
  (170, 'Villa Andrea', 'GALAPA'),
  (171, '12 de Septiembre', 'GALAPA'),
  (172, 'Barrio Arriba', 'GALAPA'),
  (173, 'Camagüey', 'GALAPA'),
  (174, 'Cruz de Jubileo', 'GALAPA'),
  (175, 'Casa Grande', 'GALAPA'),
  (176, 'El Carmen', 'GALAPA'),
  (177, 'El Libertador', 'GALAPA'),
  (178, 'El Mohán', 'GALAPA'),
  (179, 'Gerlein', 'GALAPA'),
  (180, 'La Candelaria 1', 'GALAPA'),
  (181, 'La Candelaria 2', 'GALAPA'),
  (182, 'La Florida', 'GALAPA'),
  (183, 'Las Petronitas', 'GALAPA'),
  (184, 'Las Mercedes', 'GALAPA'),
  (185, 'Los Carruajes', 'GALAPA'),
  (186, 'Manga 3 de Mayo', 'GALAPA'),
  (187, 'Manga de Pital', 'GALAPA'),
  (188, 'Manga de Rubio', 'GALAPA'),
  (189, 'Pueblito Nuevo', 'GALAPA'),
  (190, 'Salón Azul', 'GALAPA'),
  (191, 'San Francisco', 'GALAPA'),
  (192, 'San Luis', 'GALAPA'),
  (193, 'San Roque', 'GALAPA'),
  (194, 'Mundo Feliz Etapa 1 y 2', 'GALAPA'),
  (195, 'Villa Olímpica', 'GALAPA'),
  (196, 'Manga de Juan Mina', 'GALAPA'),
  (197, 'Villa Virginia', 'GALAPA'),
  (198, 'Villa Sabita', 'GALAPA'),
  (199, 'Atardeceres', 'GALAPA'),
  (200, 'Villa Celina', 'GALAPA'),
  (201, 'Gaitán', 'GALAPA'),
  (202, 'La Plaza', 'GALAPA'),
  (203, 'Punta Brava', 'GALAPA'),
  (204, 'Santa Rita', 'GALAPA'),
  (205, 'Betania', 'GALAPA'),
  (206, 'Villa María', 'GALAPA'),
  (207, 'Altos de Betania', 'GALAPA'),
  (208, 'Recreo', 'GALAPA'),
  (209, 'San Benito', 'GALAPA'),
  (210, 'San Juan Bosco', 'GALAPA'),
  (211, 'Fátima', 'GALAPA'),
  (212, 'Los Caracoles', 'GALAPA'),
  (213, 'Villa Marcela', 'GALAPA'),
  (214, '2 de Marzo II Etapa', 'GALAPA'),
  (215, 'John F. Kennedy', 'GALAPA'),
  (216, 'Los Laureles', 'GALAPA'),
  (217, 'Los Campanos', 'GALAPA'),
  (218, 'Rey José', 'GALAPA'),
  (219, 'Los Ángeles', 'GALAPA'),
  (220, 'Voz del Pueblo', 'GALAPA'),
  (221, 'Villa Carmen', 'GALAPA'),
  (222, '7 de Agosto', 'GALAPA'),
  (223, '1 de Diciembre', 'GALAPA'),
  (224, 'Los Claveles', 'GALAPA'),
  (225, 'Bella Vista', 'GALAPA'),
  (226, 'Urbanización San Carlos I', 'GALAPA'),
  (227, 'Urbanización San Carlos II', 'GALAPA'),
  (228, 'Evaristo Sourdis I', 'GALAPA'),
  (229, 'Evaristo Sourdis II', 'GALAPA'),
  (230, 'Las Camelias', 'GALAPA'),
  (231, 'Los Robles I', 'GALAPA'),
  (232, 'Los Robles II', 'GALAPA'),
  (233, 'La Alianza', 'GALAPA'),
  (234, 'Las Colinas', 'GALAPA'),
  (235, '1 de Mayo', 'GALAPA'),
  (236, 'Hospital', 'GALAPA'),
  (237, 'Tolima', 'GALAPA'),
  (238, 'Sabanita', 'GALAPA'),
  (239, 'Getsemaní', 'GALAPA'),
  (240, 'La Concepción', 'GALAPA'),
  (241, 'Los Nogales', 'GALAPA'),
  (242, 'Jagüey de Villa', 'GALAPA'),
  (243, 'Las Mercedes I', 'GALAPA'),
  (244, 'Las Mercedes II', 'GALAPA'),
  (245, 'Villa Concepción', 'GALAPA'),
  (246, 'Las Lomas', 'GALAPA'),
  (247, 'Las Quintas', 'GALAPA'),
  (248, 'Villa Esperanza', 'GALAPA'),
  (249, 'La Sabana', 'GALAPA'),
  (250, 'Villa Belén', 'GALAPA'),
  (251, 'Isabel Cristina', 'GALAPA'),
  (252, 'La Manga de la Piragua', 'GALAPA'),
  (253, 'Feria', 'GALAPA'),
  (254, 'Santander', 'GALAPA'),
  (255, 'Cascajalito', 'GALAPA'),
  (256, 'Los Manguitos', 'GALAPA'),
  (257, 'Las Melisas', 'GALAPA'),
  (258, '20 de Enero', 'GALAPA'),
  (259, 'Villa Aspros', 'GALAPA'),
  (260, 'La Bendición', 'GALAPA'),
  (261, 'Concord', 'GALAPA'),
  (262, 'Mi Habitad', 'GALAPA'),
  (263, 'Juan Mina', 'GALAPA'),
  (264, 'Arroyo de Piedra', 'GALAPA'),
  (265, 'Cascajal', 'GALAPA'),
  (266, 'Isabel López', 'GALAPA'),
  (267, 'Hibácharo', 'GALAPA'),
  (268, 'Caracolí', 'GALAPA'),
  (269, 'Campeche', 'GALAPA')
), pendientes as (
  select nuevas.*
  from nuevas
  where not exists (
    select 1
    from public.ruta_criticas as existente
    where lower(btrim(existente."CD")) = lower(nuevas.cd)
      -- La pantalla elimina el sufijo de viajes al mostrar el barrio.
      and lower(btrim(regexp_replace(
        existente."RUTA", '\s*\(\s*[0-9]+\s+VIAJES?\s*\)\s*$', '', 'i'
      ))) = lower(nuevas.ruta)
  )
), ultimo as (
  select coalesce(max("#"), 0) as numero
  from public.ruta_criticas
), insertadas as (
  insert into public.ruta_criticas ("#", "RUTA", "CD")
  overriding system value
  select ultimo.numero + row_number() over (order by pendientes.orden),
         pendientes.ruta,
         pendientes.cd
  from pendientes cross join ultimo
  returning "#", "RUTA", "CD"
)
select count(*) as rutas_agregadas from insertadas;

-- Si "#" usa serial/identity, sincroniza su secuencia con los IDs insertados.
do $$
declare
  secuencia text;
  maximo bigint;
  valor_secuencia bigint;
begin
  secuencia := pg_get_serial_sequence('public.ruta_criticas', '#');
  if secuencia is not null then
    select max("#") into maximo from public.ruta_criticas;
    execute format('select last_value from %s', secuencia::regclass)
      into valor_secuencia;
    if maximo is not null then
      perform setval(secuencia::regclass, greatest(maximo, valor_secuencia), true);
    end if;
  end if;
end;
$$;

commit;
