-- Ejecutar en el SQL Editor del proyecto Supabase de la aplicación.
-- Compatible con /api/public/critical-routes y /api/people/critical-routes/hazards.
-- No elimina registros existentes. Si la tabla ya existe, CREATE TABLE no cambia sus columnas.
begin;

create table if not exists public.ruta_criticas_riesgos (
  id bigint generated by default as identity primary key,
  ruta text not null check (length(btrim(ruta)) > 0),
  tipo text not null check (length(btrim(tipo)) > 0),
  descripcion text not null check (length(btrim(descripcion)) > 0),
  latitud numeric(10,7) not null check (latitud between -90 and 90),
  longitud numeric(10,7) not null check (longitud between -180 and 180),
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

-- Una tabla creada previamente puede limitar tipo a categorías de riesgo.
-- El formulario de ubicaciones también guarda aquí la cédula RR.
-- NOT VALID conserva los registros históricos y aplica la regla a nuevas escrituras.
alter table public.ruta_criticas_riesgos
  drop constraint if exists ruta_criticas_riesgos_tipo_check;
alter table public.ruta_criticas_riesgos
  add constraint ruta_criticas_riesgos_tipo_check
  check (
    tipo in ('cables_bajos', 'via_danada', 'inundacion', 'cierre', 'peligro')
    or tipo ~ '^[0-9]+$'
  ) not valid;

comment on table public.ruta_criticas_riesgos is
  'Ubicaciones y reportes utilizados por el formulario de coordenadas y el modo TV.';
comment on column public.ruta_criticas_riesgos.ruta is
  'Nombre del cliente o ruta enviado por el formulario actual.';
comment on column public.ruta_criticas_riesgos.tipo is
  'Cédula RR en el formulario de coordenadas, o categoría de peligro en rutas críticas. Se guarda como texto.';

create index if not exists ruta_criticas_riesgos_activo_id_idx
  on public.ruta_criticas_riesgos (activo, id desc);

alter table public.ruta_criticas_riesgos enable row level security;

-- El formulario de coordenadas se usa antes de iniciar sesión y el mapa
-- público consulta los puntos activos. No se permite borrar como anónimo.
grant select, insert on public.ruta_criticas_riesgos to anon, authenticated;
grant delete on public.ruta_criticas_riesgos to authenticated;
grant all on public.ruta_criticas_riesgos to service_role;

-- Resuelve la secuencia real, tanto para una tabla nueva como para una existente.
do $$
declare
  coordinate_sequence text;
begin
  coordinate_sequence := pg_get_serial_sequence('public.ruta_criticas_riesgos', 'id');
  if coordinate_sequence is not null then
    execute format('grant usage on sequence %s to anon, authenticated, service_role', coordinate_sequence);
  end if;
end
$$;

drop policy if exists ubicaciones_read_active on public.ruta_criticas_riesgos;
create policy ubicaciones_read_active on public.ruta_criticas_riesgos
  for select to anon, authenticated using (activo = true);

drop policy if exists ubicaciones_insert_active on public.ruta_criticas_riesgos;
create policy ubicaciones_insert_active on public.ruta_criticas_riesgos
  for insert to anon, authenticated with check (activo = true);

-- Mismos usuarios administradores/People definidos por la aplicación.
drop policy if exists ubicaciones_staff_read on public.ruta_criticas_riesgos;
create policy ubicaciones_staff_read on public.ruta_criticas_riesgos
  for select to authenticated
  using (lower((select auth.jwt()) ->> 'email') in (
    'admin@bavaria-seguimiento.com', 'saul808c@gmail.com',
    'adminare@gmail.com', 'people@transporte.com'
  ));

drop policy if exists ubicaciones_staff_delete on public.ruta_criticas_riesgos;
create policy ubicaciones_staff_delete on public.ruta_criticas_riesgos
  for delete to authenticated
  using (lower((select auth.jwt()) ->> 'email') in (
    'admin@bavaria-seguimiento.com', 'saul808c@gmail.com',
    'adminare@gmail.com', 'people@transporte.com'
  ));

notify pgrst, 'reload schema';
commit;

-- INSERT de ejemplo: sustituye por datos reales y ejecútalo solo si deseas
-- agregar un registro manualmente. El formulario realiza este INSERT por API.
-- insert into public.ruta_criticas_riesgos
--   (ruta, tipo, descripcion, latitud, longitud, activo)
-- values
--   ('Cliente de ejemplo', '12345678', 'Descripción de la ubicación',
--    10.9300000, -74.8500000, true);

-- Verificación:
select id, ruta, tipo, descripcion, latitud, longitud, activo
from public.ruta_criticas_riesgos
order by id desc
limit 20;
