import type { Vehiculo } from "./types";

export const initialVehicles: Vehiculo[] = [
  {
    mes: "Junio",
    cd: "BAQ",
    transportista: "Translog Caribe",
    llave: "BAQ-COKSP179",
    transporte: "DT-10458",
    centro: "Punto Corona",
    codTransportista: "TR-084",
    fechaDt: "2026-06-11",
    fechaDespacho: "2026-06-11",
    vehiculo: "COKSP179",
    responsable: "Luis Avendano",
    territorio: "Soledad",
    viaje: "VJ-001",
    bloque: "AM",
    cajas: 261,
    hl: 24.2,
    clientes: 13,
    visitados: 4,
    horaSalida: "07:31",
    peso: 4343,
    capacidad: 8800,
    validadorPeso: "OK",
    avanceRuta: "31%",
    status: "En ruta",
    horaLlegada: "Pendiente",
    tiempoRuta: "02:18",
    metaRelevo: "No aplica",
    horaInicioRelevo: "-",
    clasificacionRelevo: "Sin relevo",
    alertaSifPotencial: "No",
    relevador: "-",
    causalDesviado: "-",
    clasificacionOnTime: "On time",
    recargue: "No",
  },
  {
    mes: "Junio",
    cd: "BAQ",
    transportista: "Translog Caribe",
    llave: "BAQ-COLJT750",
    transporte: "DT-10459",
    centro: "Punto Corona",
    codTransportista: "TR-084",
    fechaDt: "2026-06-11",
    fechaDespacho: "2026-06-11",
    vehiculo: "COLJT750",
    responsable: "Jonar Jesus",
    territorio: "Soledad",
    viaje: "VJ-002",
    bloque: "AM",
    cajas: 426,
    hl: 40.7,
    clientes: 14,
    visitados: 2,
    horaSalida: "07:33",
    peso: 7043,
    capacidad: 9200,
    validadorPeso: "OK",
    avanceRuta: "14%",
    status: "En ruta",
    horaLlegada: "Pendiente",
    tiempoRuta: "02:16",
    metaRelevo: "No aplica",
    horaInicioRelevo: "-",
    clasificacionRelevo: "Sin relevo",
    alertaSifPotencial: "No",
    relevador: "-",
    causalDesviado: "-",
    clasificacionOnTime: "En observacion",
    recargue: "No",
  },
  {
    mes: "Junio",
    cd: "BAQ",
    transportista: "Aliado Norte",
    llave: "BAQ-COLCN035",
    transporte: "DT-10460",
    centro: "Punto Corona",
    codTransportista: "TR-112",
    fechaDt: "2026-06-11",
    fechaDespacho: "2026-06-11",
    vehiculo: "COLCN035",
    responsable: "Sin Asistencia",
    territorio: "Soledad",
    viaje: "VJ-003",
    bloque: "AM",
    cajas: 571,
    hl: 51.4,
    clientes: 19,
    visitados: 1,
    horaSalida: "08:02",
    peso: 8646,
    capacidad: 9200,
    validadorPeso: "Al limite",
    avanceRuta: "5%",
    status: "Cargando",
    horaLlegada: "Pendiente",
    tiempoRuta: "01:47",
    metaRelevo: "Revisar",
    horaInicioRelevo: "-",
    clasificacionRelevo: "Pendiente",
    alertaSifPotencial: "Si",
    relevador: "-",
    causalDesviado: "Sin asistencia",
    clasificacionOnTime: "Riesgo",
    recargue: "No",
  },
  {
    mes: "Junio",
    cd: "BAQ",
    transportista: "Distribuciones Costa",
    llave: "BAQ-COLRM418",
    transporte: "DT-10461",
    centro: "Punto Corona",
    codTransportista: "TR-067",
    fechaDt: "2026-06-11",
    fechaDespacho: "2026-06-11",
    vehiculo: "COLRM418",
    responsable: "Andrea Torres",
    territorio: "Barranquilla",
    viaje: "VJ-004",
    bloque: "PM",
    cajas: 344,
    hl: 32.8,
    clientes: 16,
    visitados: 11,
    horaSalida: "07:48",
    peso: 5960,
    capacidad: 9000,
    validadorPeso: "OK",
    avanceRuta: "69%",
    status: "En ruta",
    horaLlegada: "Pendiente",
    tiempoRuta: "02:01",
    metaRelevo: "No aplica",
    horaInicioRelevo: "-",
    clasificacionRelevo: "Sin relevo",
    alertaSifPotencial: "No",
    relevador: "-",
    causalDesviado: "-",
    clasificacionOnTime: "On time",
    recargue: "Si",
  },
];
